spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://127.0.0.1:5432/crud-spring-kipper"
    username: postgres
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextutal_creation: true

api:
  security:
    token:
      secret: "${JWT_SECRET:my-secret-key}"